-- SIGN

INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('ARIES', 'Овен', 'sign description', 20, 03, 19, 04);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('TAURUS', 'Телец', 'sign description', 20, 04, 20, 05);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('GEMINI', 'Близнецы', 'sign description', 21, 05, 22, 06);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('CANCER', 'Рак', 'sign description', 21, 06, 22, 07);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('LEO', 'Лев', 'sign description', 23, 07, 22, 08);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('VIRGO', 'Дева', 'sign description', 23, 08, 22, 09);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('LIBRA', 'Весы', 'sign description', 23, 09, 22, 10);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('SCORPIO', 'Скорпион', 'sign description', 23, 10, 21, 11);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('SAGITTARIUS', 'Стрелец', 'sign description', 22, 11, 21, 12);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('CAPRICORN', 'Козерог', 'sign description', 22, 12, 20, 01);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('AQUARIUS', 'Водолей', 'sign description', 21, 01, 18, 02);
INSERT INTO SIGN (NAME, DISPLAY_NAME, DESCRIPTION, START_DAY, START_MONTH, END_DAY, END_MONTH) VALUES ('PIESCES', 'Рыбы', 'sign description', 19, 02, 19, 03);

-- HORO_TYPE

INSERT INTO HORO_TYPE (NAME) VALUES ('DAILY');
INSERT INTO HORO_TYPE (NAME) VALUES ('WEEKLY');
INSERT INTO HORO_TYPE (NAME) VALUES ('MONTHLY');
INSERT INTO HORO_TYPE (NAME) VALUES ('YEARLY');
